### ISSUE TITLE
Splitting swagger files error

### ISSUE THREAD

**Issue by vimalloc** [zalando/connexion#419] opened 2017-03-21 17:16 UTC
### Description
When attempting to split a large swagger configuration file into smaller modular parts I am getting a ```SwaggerValidationError```

See:
* https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/REUSE.md
* https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-8-splitting-specification-file/

### Expected behaviour
Breaking swagger configurations into smaller files and referencing them should not produce an error

 ```
$ref: 'filename.yaml/#Reference'
```

### Actual behaviour
The references to other files raises this error:
 ``` 
swagger_spec_validator.common.SwaggerValidationError: unknown url type: 'filename.yaml/'
```

### Steps to reproduce
test.yaml
```yaml
swagger: "2.0"

info:
  title: "Test"
  version: "1.0"

basePath: /v1.0

produces:
  - application/json

consumes:
  - application/json

paths:
  /foo:
    get:
      operationId: test.foo
      responses:
        200:
          description: Foo
          schema:
            $ref: 'foo.yaml/#Foo'
```

foo.yaml
```yaml
Foo:
  description: Test foo
  type: object
  required:
    - foo
  properties:
    foo:
      type: string
      example: 'foo'
```

test.py:
```python
#!/usr/bin/env python3
import connexion
app = connexion.App(__name__, 9091)

def foo():
    return {'foo': 'bar'}

if __name__ == '__main__':
    app.add_api('test.yaml', validate_responses=True, strict_validation=True)
    app.run()
```

### Additional info:
Python 3.6.0
Conexion Version: 1.1.5

**Comment by rafaelcaricio** [comment] 2017-03-21 19:19
Duplicate of https://github.com/zalando/connexion/issues/254

**Closed by rafaelcaricio** 2017-03-21 19:19 UTC
