### ISSUE TITLE
OneOf does not work for parameters inside a schema

### ISSUE THREAD

**Issue by BobDG** [zalando/connexion#804] opened 2018-11-30 13:37 UTC
### Description
When I use oneOf inside a schema to describe that a property can be either an integer or a string, the validation does not fail but when I actually call that method in Swagger, with either an integer or a string, I get an error saying: "Body property 'property_name' not defined in body schema:

### Expected behaviour
It should send the property correctly to my api method

### Actual behaviour
When calling the method it gives the error  "Body property 'property_name' not defined in body schema.

### Steps to reproduce
Create a schema where one of the properties uses a oneOf:
schemaname:
      type: "object"
      properties:
        propertyname:
          oneOf:
            - type: "integer"
            - type: "string"

### Additional info:

Output of the commands:

- `python --version`
Python 3.7.0
- `pip show connexion | grep "^Version\:"`
Version: 2.0.2

**Comment by dtkav** [comment] 2018-12-01 19:42
Closing as duplicate of #691

**Closed by dtkav** 2018-12-01 19:42 UTC

**Comment by BobDG** [comment] 2018-12-02 09:10
@dtkav Just checking, I saw the other issue before I posted mine but that one is specifically about nested schemas where the final oneOf is nested within another schema. My issue is less complex and simply about a parameter type, no nesting involved.

But if you're certain the bug of that issue also causes my issue , then closing it is logically of course :)
