### ISSUE TITLE
Not passing get params to controller function

### ISSUE THREAD

**Issue by andwxh** [zalando/connexion#135] opened 2016-02-03 09:57 UTC
I have a swagger endpoint like this:

```
paths:
  /query:
    get:
      summary: Query material's information
      description: |
        This interface using application token to authorize a client, and return the material's information under specified orderId.
      parameters:
        - name: token
          in: query
          description: Api token of the client.
          required: true
          type: string
        - name: order_id
          in: query
          description: Target orderId.
          required: true
          type: number
          format: int64
      tags:
        - Query
      responses:
        '200':
          description: Material informations.
          schema:
            $ref: '#/definitions/MaterialInfo'
        '401':
          description: Invalid token.
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
```
And I have used swagger editor to generate a server, I got two _.py_ files:
**app.py:**
```
#!/usr/bin/env python3

import connexion

if __name__ == '__main__':
   app = connexion.App(__name__, 8889, specification_dir='./swagger/')
   app.add_api('swagger.yaml', arguments={'title': 'Server-to-server api for querying material information of PLUS platform.'})
   app.run()
```
**default_controller.py:**
```

def query_get(token, orderId) -> str:
   return 'do some magic!'
```
It looks fine.
I have tried using some wrong params, it returns a good 400 status with error information.

But when I using correct params, here comes **500** with no details information.
I have read the documents and connexion-examples, it looks like nothing wrong with this generated code above.

And after reading the connexion's code and debugging, I found that **connexion call _query_get_ with no arguments.**
There was an "_Exception: query_get() missing 2 required positional arguments: 'token' and 'orderId' _" raised.

I changed **default_controller.py** to:
```
from flask import request


def query_get():
    token = request.args.get("token")
    orderId = request.args.get("order_id")
    return "ok"
```
Then this endpoint works fine.

In this case, connexion verified the params but forget to pass it to controller function.

(PS: I'm using python 3.4.3 with connexion 1.0.49)

**Comment by hjacobs** [comment] 2016-02-03 11:14
@andwxh the query parameter names must match exactly: compare "orderId" and "order_id" --- if you use `order_id` in Python too (which also follows Python coding conventions), it should work (?)

**Comment by andwxh** [comment] 2016-02-03 11:33
@hjacobs you are right. It works!
It seems that swagger-editor generates a wrong param name.
It's a little confusing that there is no searching result about this issue.
Thank you for your answer.

**Comment by hjacobs** [comment] 2016-02-03 11:39
@andwxh maybe you can raise the issue in swagger-codegen or swagger-editor or wherever the root cause lies.
Thanks!

**Comment by andwxh** [comment] 2016-02-04 03:46
@hjacobs yep, I will read the code of swagger-editor, trying to find out what cause this problem.

By the way, when I using the new function param, here comes a new issue. The server returns **500** after the first time of wrong param.

The new controller function is like this:
`def query_get(token, order_id):`

After I start this server, I have tried some requests:
> 1 127.0.0.1 - - [04/Feb/2016 11:28:12] "GET /v1/query?token=foo&ordd=1000 HTTP/1.1" 400 -
> 2 127.0.0.1 - - [04/Feb/2016 11:28:16] "GET /v1/query?token=foo&o=1000 HTTP/1.1" 400 -
> 3 127.0.0.1 - - [04/Feb/2016 11:28:24] "GET /v1/query?token=foo&orderid=1000 HTTP/1.1" 400 -

> 4 127.0.0.1 - - [04/Feb/2016 11:28:27] "GET /v1/query?token=foo&order_id=1000 HTTP/1.1" **200** -

> 5 127.0.0.1 - - [04/Feb/2016 11:28:32] "GET /v1/query?token=foo&**order_i**=1000 HTTP/1.1" **500** -

> 6 127.0.0.1 - - [04/Feb/2016 11:28:59] "GET /v1/query?token=foo&ordd=1000 HTTP/1.1" 500 -
> 7 127.0.0.1 - - [04/Feb/2016 11:29:10] "GET /v1/query?token=foo&o=1000 HTTP/1.1" 500 -
> 8 127.0.0.1 - - [04/Feb/2016 11:29:16] "GET /v1/query?token=foo&orderid=1000 HTTP/1.1" 500 -

The first 3 requests with wrong params were fine, it returns 400 with error information.
And the 4th request had correct params, it returns 200 with expected data.
The 5th request using a wrong param again, this time the server returns **500**.
Then at the 6-8 request, I'm trying to use the **same params in request 1-3**, but all returns 500.

For request 5-8, connexion calling query_get with params like this: 

> args: (), kwargs: {'token': 'foo'}

And I got an exception:

> Exception: query_get() missing 1 required positional argument: 'order_id'

It seems that after a correct request, param checking will not work anymore.

**Comment by elezar** [comment] 2016-02-04 05:51
The 500 on the second call sounds like Issue #131.

On Thu, 4 Feb 2016 04:46 andwxh <notifications@github.com> wrote:

> @hjacobs <https://github.com/hjacobs> yep, I will read the code of
> swagger-editor, trying to find out what cause this problem.
>
> By the way, when I using the new function param, here comes a new issue.
> The server returns *500* after the first time of wrong param.
>
> The new controller function is like this:
> def query_get(token, order_id):
>
> After I start this server, I have tried some requests:
>
> 1 127.0.0.1 - - [04/Feb/2016 11:28:12] "GET /v1/query?token=foo&ordd=1000
> HTTP/1.1" 400 -
> 2 127.0.0.1 - - [04/Feb/2016 11:28:16] "GET /v1/query?token=foo&o=1000
> HTTP/1.1" 400 -
> 3 127.0.0.1 - - [04/Feb/2016 11:28:24] "GET
> /v1/query?token=foo&orderid=1000 HTTP/1.1" 400 -
>
> 4 127.0.0.1 - - [04/Feb/2016 11:28:27] "GET
> /v1/query?token=foo&order_id=1000 HTTP/1.1" *200* -
>
> 5 127.0.0.1 - - [04/Feb/2016 11:28:32] "GET /v1/query?token=foo&*order_i*=1000
> HTTP/1.1" *500* -
>
> 6 127.0.0.1 - - [04/Feb/2016 11:28:59] "GET /v1/query?token=foo&ordd=1000
> HTTP/1.1" 500 -
> 7 127.0.0.1 - - [04/Feb/2016 11:29:10] "GET /v1/query?token=foo&o=1000
> HTTP/1.1" 500 -
> 8 127.0.0.1 - - [04/Feb/2016 11:29:16] "GET
> /v1/query?token=foo&orderid=1000 HTTP/1.1" 500 -
>
> The first 3 requests with wrong params were fine, it returns 400 with
> error information.
> And the 4th request had correct params, it returns 200 with expected data.
> The 5th request using a wrong param again, this time the server returns
> *500*.
> Then at the 6-8 request, I'm trying to use the *same params in request
> 1-3*, but all returns 500.
>
> For request 5-8, connexion calling query_get with params like this:
>
> args: (), kwargs: {'token': 'foo'}
>
> And I got an exception:
>
> Exception: query_get() missing 1 required positional argument: 'order_id'
>
> It seems that after a correct request, param checking will not work
> anymore.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zalando/connexion/issues/135#issuecomment-179604282>.
>
-- 
Evan Lezar
www.evanlezar.com

**Comment by hjacobs** [comment] 2016-02-04 08:37
@andwxh this sounds like #131 which was fixed in https://github.com/zalando/connexion/releases/tag/1.0.52 --- please try upgrading:

```
sudo pip3 install --upgrade connexion
```
(command assumes you are using a globally installed Connexion lib with Python 3)

**Closed** 2016-02-17 10:33 UTC
