### ISSUE TITLE
Date times using + (eastward) time zone offsets throw error

### ISSUE THREAD

**Issue by nicole-fp** [zalando/connexion#353] opened 2016-11-29 17:51 UTC
### Description
Date-times with timezones using + designation return invalid timezone error

### Expected bahaviour
No error, date time using +00:00 timezones are accepted

### Actual behaviour
Invalid date-time error is thrown

### Steps to reproduce
Steps:
Compare 1985-04-12T23:20:50.52-10:00 to 1985-04-12T23:20:50.52+10:00

### Additional info:

python 3.5.2
connexion version 1.0.129

**Comment by jmcs** [comment] 2016-11-30 10:17
Can you post a code snippet or the actual exception with stacktrace?

**Comment by tomas-fp** [comment] 2016-11-30 10:25
I think I found the origin the issue. 

Basically, ISO compliant datetime expressions, such as `2016-11-29T14:22:36+00:00`, when exposed via raw URL query param, the datetime value must be URL safe and encoded accordingly first. Most HTTP clients do this transparently, but others do not.

The above datetime must be encoded as `2016-11-29T14:22:36%2B00:00` in order to turn sensitive characters URL safe. That works as expected and can be parsed accordingly by connexion/Swagger parser.

**Comment by hjacobs** [comment] 2016-11-30 10:42
URL encoding issue, not a bug in Connexion -> closing this.

**Closed by hjacobs** 2016-11-30 10:42 UTC
Labels: question
