### ISSUE TITLE
Body parameter in openapi 3

### ISSUE THREAD

**Issue by cziebuhr** [zalando/connexion#799] opened 2018-11-27 17:34 UTC
### Description
If the body schema specifies `type: object`, `operations.openapi._get_body_argument` deletes all arguments not specified in `properties`. What's the reason for tampering the body parameter, even if it is actually valid? It doesn't happen for swagger 2, nor for other datatypes or when `properties` is used without `type: object`.

### Expected behaviour
Seeing output `{'bar': 123, 'baz': 456}`.

### Actual behaviour
Seeing output `{'bar': 123}`.

### Steps to reproduce
Take this openapi schema, handler and request:
```
paths:
  /foo:
    post:
      operationId: fakeapi.hello.foo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bar: {}
      responses:
        200:
          description: Success
```
```
def foo(body):
  print(body)
```
```
app_client.post('/v1.0/foo', data=json.dumps({'bar': 123, 'baz': 456}), content_type='application/json')
```
### Additional info:

Output of the commands:

- `python --version`
Python 3.5.2
- `pip show connexion | grep "^Version\:"`
Version: 2.0.2

**Comment by dtkav** [comment] 2018-11-28 08:03
duplicate of #781 
should be addressed in #789

**Comment by dtkav** [comment] 2018-11-28 08:14
Closing as duplicate of #781 - thanks for the detailed ticket.
This was simply due to misreading the spec on my part. Sorry about that.

**Closed by dtkav** 2018-11-28 08:14 UTC

**Comment by phamlehuy53** [comment] 2020-10-01 02:13
This helped me [](https://github.com/zalando/connexion#automatic-parameter-handling)
