### ISSUE TITLE
Multiple API-specifications

### ISSUE THREAD

**Issue by JakartaLaw** [zalando/connexion#1094] opened 2019-12-05 22:16 UTC
### Description

I try to add multiple api-specifications:
swagger1.yaml
swagger2.yaml

and in the application code:

app.add_api("swagger1.yaml")
app.add_api("swagger2.yaml")

### Expected behaviour

Expect to start api with one long swagger documentation

### Actual behaviour

`AssertionError: A name collision occurred between blueprints <flask.blueprints.Blueprint object at 0x7f8e1ee2ea90> and <flask.blueprints.Blueprint object at 0x7f8e1ee2e6d0>. Both share the same name "". Blueprints that are created on the fly need unique names`

### Steps to reproduce

mentioned above

### Additional info:

Maybe this is expected behavior, but the documentation does not specify anything about multiple swagger docs. If this is expected behavior, im sorry for raising the issue.

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by msoodb** [comment] 2019-12-06 15:33
https://github.com/zalando/connexion/issues/254#issuecomment-497194240

**Comment by dtkav** [comment] 2019-12-18 03:04
Hi @msoodb - it sounds like you're expecting that those specs would be merged?
If so, I don't think that's the intended behavior in connexion.

If what you want is two separate apis, each with a different spec, then you should be able to do that by passing in distinct `base_path` routes to `app.add_api()`

**Comment by samkots** [comment] 2021-03-10 15:58
I was expecting the same @dtkav.
It works with URL-based versioning approach as the URLs themselves are different.

But if I'm using header-based or media-type-based versioning approach, then my URLs(base paths) will be same across versions:
Example: `petstore-v1.yaml` and `petstore-v2.yaml` with same URL.

How do we server both the versions simultaneously?

**Comment by RobbeSneyders** [comment] 2021-07-20 15:36
For merging multiple API-specifications, please check #254.
For header-based or media-type-based versioning, please check #1346.

**Closed by RobbeSneyders** 2021-07-20 15:36 UTC
Labels: question

**Comment by samkots** [comment] 2021-08-21 16:03
Thanks @RobbeSneyders :)
