### ISSUE TITLE
Support for Open API Spec v3.0.0

### ISSUE THREAD

**Issue by jakul** [zalando/connexion#502] opened 2017-08-03 10:01 UTC
[OpenAPI Spec v3.0.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md) is now the current version of the specification. Are there plans for Connexion to support it?

**Comment by rafaelcaricio** [comment] 2017-08-07 14:46
We should. But no work was started yet.

**Comment by tomas-fp** [comment] 2017-08-07 19:28
Duplicated. See: #420

**Comment by hjacobs** [comment] 2017-08-07 19:32
Closing as duplicate of #420

**Closed by hjacobs** 2017-08-07 19:32 UTC
Labels: duplicate
