### ISSUE TITLE
Complex validation for query parameters doesn't work

### ISSUE THREAD

**Issue by lovesuper** [zalando/connexion#932] opened 2019-05-02 15:47 UTC
### Description
I have write come custom validator for UUID type validation, and declared following statements:
```
uid_path:
  description: Some unique identifier of some entity
  in: path
  name: uid_path
  required: true
  schema:
    format: x_uid
    type: string
```
### Expected behaviour

It would validate my path parameter, and deny such strings as "abcd"

### Actual behaviour

It wouldn't and such string as "abcd" will get to the View

### Steps to reproduce

Even following simple code doesn't work:
```
uid_path:
  description: Some unique identifier of some entity
  in: path
  name: uid_path
  required: true
  schema:
    enum: ["A", "B", "C", "D"]
    type: string
```
It allows ANY string to pass through . But not integer to be honest

### Additional info:

Output of the commands:

- `Python 3.7.3`
- `Version: 2018.0.dev1`

**Comment by rafaelcaricio** [comment] 2019-05-03 10:48
Hi @lovesuper ,

Have you followed the cookbook from this page: https://connexion.readthedocs.io/en/latest/cookbook.html#custom-type-format ?

Please notice the part that mention:
> Keep in mind that the format checkers should be defined and registered before you run your application server.

That means you need to register your custom format before instantiating `FlaskApp`.

If you don't manage to get it to work, would be nice to get to see some of your code that is not working. Maybe you can isolate in a simple example (minimal lines of code) how to reproduce what you are experiencing?

**Comment by lovesuper** [comment] 2019-05-03 11:07
@rafaelcaricio , Hello.

Have you read the text above? I wrote that even classic _enum_ does not work for me. Not only x_uid (custom validator) but even re pattern or similar type checker additions. This is working for json body validation, but not for path parameters. That's the thing.

**Comment by rafaelcaricio** [comment] 2019-05-03 11:12
Hi @lovesuper,

Have you read the text above? I need to see a minimal reproduction of this problem so I can try to help you.

**Comment by rafaelcaricio** [comment] 2019-05-03 11:29
I just realized that you're trying to use custom formatters on "url" type parameter. Indeed, it will not work. It won't work because custom format is a feature of JSON, thus it only work on JSON payloads.

**Comment by rafaelcaricio** [comment] 2019-05-03 11:40
You can use regular expressions there and then it should work. Example: https://github.com/zalando/connexion/blob/44ea9336fe79ddb9592942b405a663d2e3aa612c/examples/openapi3/sqlalchemy/openapi.yaml#L91

**Comment by rafaelcaricio** [comment] 2019-05-03 11:41
Please close this ticket if this works for you.

**Comment by lovesuper** [comment] 2019-05-03 11:43
@rafaelcaricio yes! This is really works! Sorry 4 bothering.

**Closed** 2019-05-03 11:43 UTC
Labels: question
