### ISSUE TITLE
Split YAML specification file

### ISSUE THREAD

**Issue by mvrogowski** [zalando/connexion#372] opened 2017-01-02 13:30 UTC
### Description

It's not possible to split YAML API specifications file.

### Expected behaviour

I want to get something like this:

- swagger/
    - wifiuseradmin.yaml
    - definitions.yaml
    - parameters.yaml
    - paths.yaml

### Actual behaviour

When start application, I got the following:

`2017-01-02 13:02:01,706 [DEBUG] connexion.app - Root Path: /app/wifiuseradmin`
`2017-01-02 13:02:01,707 [DEBUG] connexion.app - Specification directory: /app/wifiuseradmin/swagger`
`2017-01-02 13:02:01,707 [DEBUG] connexion.app - Setting error handlers`
`2017-01-02 13:02:01,708 [DEBUG] connexion.app - Adding API: wifiuseradmin.yaml`
`2017-01-02 13:02:01,708 [DEBUG] connexion.api - Loading specification: /app/wifiuseradmin/swagger/wifiuseradmin.yaml`
`2017-01-02 13:02:01,737 [DEBUG] connexion.api - Read specification`
`Traceback (most recent call last):`
` File "./spawn_server.py", line 1, in <module>`
`     from app import application`
`   File "./app.py", line 24, in <module>
`     app.add_api('wifiuseradmin.yaml')`
`   File "/usr/lib/python2.7/site-packages/connexion/app.py", line 149, in add_api
     debug=self.debug)`
`   File "/usr/lib/python2.7/site-packages/connexion/api.py", line 106, in __init__`
`     self.specification = compatibility_layer(self.specification)`
`   File "/usr/lib/python2.7/site-packages/connexion/api.py", line 35, in compatibility_layer`
`     for method_name, method_def in methods_available.items():`
` AttributeError: 'str' object has no attribute 'items'`

### Steps to reproduce

Just split the files and try to start application.

### Additional info:

Output of the commands:

- `python --version`
Python 2.7.12

- `pip show connexion | grep "^Version\:"`
Version: 1.0.129

**Comment by hjacobs** [comment] 2017-01-02 14:57
This looks like a duplicate of #254

**Closed by hjacobs** 2017-01-02 14:57 UTC
Labels: duplicate
