### ISSUE TITLE
what is the error in this code?

### ISSUE THREAD

**Issue by Yashdey** [zalando/connexion#1276] opened 2020-08-06 06:27 UTC
### Description
GIVING ERROR:

* Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
INFO:werkzeug: * Restarting with stat
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

### Additional info:

Output of the commands:

- `python --version3.5`
- `pip show connexion | grep "^Version\:"`
![Picture1](https://user-images.githubusercontent.com/69249748/89499129-1d725d80-d7dd-11ea-88f0-4cb2ea5624b6.png)

**Comment by cchadha2** [comment] 2020-08-12 21:13
Could you run the `%tb` command and provide the full traceback?

**Comment by Ruwann** [comment] 2021-07-16 06:50
It's unclear from the info you provided what the problem is. This could also be flask-related as you are trying to run a flask server in a jupyter notebook with `debug=True` ([Stackoverflow Question](https://stackoverflow.com/questions/41831929/debug-flask-server-inside-jupyter-notebook))

Closing due to lack of information. Feel free to reopen if you can provide some more info.

**Closed by Ruwann** 2021-07-16 06:50 UTC
