### ISSUE TITLE
minLength/maxLength not enforced on string (not part of object) type parameter

### ISSUE THREAD

**Issue by Roiera** [zalando/connexion#1336] opened 2021-01-15 11:49 UTC
Hi,

We have an endpoint that receives PUT method and a string as input.
I've added min/maxLength limitations on the input but it doesn't seem to be enforced.
What might be the reason for this behavior?

www-data@aa01e64be3de:/usr/src/app$ python --version
Python 3.6.12
www-data@aa01e64be3de:/usr/src/app$ pip show connexion | grep "^Version\;"
flag.
Version: 2.7.0

**Comment by KBA07** [comment] 2021-02-02 10:45
@Roiera It would be helpful if you included the API definition yaml file/snippet along with the exact requested API call.

**Comment by Ruwann** [comment] 2021-07-08 12:36
Hi @Roiera , I'm not able to reproduce your issue. When adapting the swagger2/helloworld example, a `400 Bad Request` is returned when the string is too short:

```
{
  "detail": "'dav' is too short\n\nFailed validating 'minLength' in schema:\n    {'description': 'Name of the person to greet.',\n     'in': 'path',\n     'minLength': 4,\n     'name': 'name',\n     'type': 'string'}\n\nOn instance:\n    'dav'",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```

As @KBA07 said, could you provide an example and the API definition you are using?

**Comment by Ruwann** [comment] 2021-07-20 12:01
Closing for now, feel free to reopen if you can provide some more information

**Closed by Ruwann** 2021-07-20 12:01 UTC
Labels: waiting contributor feedback

**Comment by glockenbach** [comment] 2024-02-22 12:23
In connexion 3: If you are adding a custom validator, make sure to extend the existing `connexion.validators.VALIDATOR_MAP`. The default validators will otherwise be overwritten. 

https://connexion.readthedocs.io/en/latest/validation.html#custom-validators
