### ISSUE TITLE
Impossible to reference local files

### ISSUE THREAD

**Issue by kapouille** [zalando/connexion#461] opened 2017-06-06 09:33 UTC
### Description

`connexion` doesn't appear to be able to resolve local files `$ref` references, resulting in an exception being thrown.

### Expected behaviour

`$ref` should be able to reference local files.

### Actual behaviour

When using relative references as defined in https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#relative-files-with-embedded-schema-example connexion fails with the following exception:

```python traceback
  ... SNIP... 
  File "/home/snip/.venv/lib/python3.6/site-packages/jsonschema/validators.py", line 366, in resolving
    url, resolved = self.resolve(ref)
  File "/home/snip/.venv/lib/python3.6/site-packages/jsonschema/validators.py", line 375, in resolve
    return url, self._remote_cache(url)
  File "/home/snip/.venv/lib/python3.6/site-packages/jsonschema/validators.py", line 385, in resolve_from_url
    raise RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: unknown url type: 'definitions.yaml'
```

Tracing the code, it would appear that `connexion` relies on the `jsonschema` library to resolve all `$ref` references. Unfortunately, as far as I know, Json Schema doesn't support relative path file references, and in that specific implementation, the fallback mechanism is to use `urllib`'s `urlopen`... Which doesn't manage to open the file.

### Steps to reproduce

Using relative file `$ref`

### Additional info:

We may be able to alter the implementation by altering the value of the `$ref` values we provide to `jsonschema`.

For instance, if we had this OpenAPI reference: 
```yaml
$ref: "definitions.yaml#/Pet"
```

We should be able to overcome `jsonschema`'s limitation by altering the `$ref` value in such a fashion that it's able to open it in `urlopen`:

```yaml
$ref: "file:///absolute/path/to/definitions.yaml#/Pet"`
```

**Comment by rafaelcaricio** [comment] 2017-06-16 12:20
Long discussion going on at https://github.com/zalando/connexion/issues/254

**Comment by dtkav** [comment] 2018-12-17 06:44
I'm going to close this as a duplicate of #254

**Closed by dtkav** 2018-12-17 06:44 UTC
Labels: duplicate, enhancement, help wanted
