### ISSUE TITLE
openapi.py does not support `anyOf` in additionalProperties

### ISSUE THREAD

**Issue by ioggstream** [zalando/connexion#1292] opened 2020-09-11 14:01 UTC
## I expect

additionalProperties to support `anyOf`

## Instead

it does not. see

https://github.com/zalando/connexion/blob/1ed14fbde5be3d144760fec4982e90064f151e88/connexion/operations/openapi.py#L325

**Comment by prometheas** [comment] 2020-11-11 20:39
I found this issue because I'm struggling with behavior I suspect to be a bug involving the (mis)handling of the `additionalProperties` flag… sadly, I am unable to determine whether whatever this issue seeks to report has anything to do with my problem.

That's my problem, of course. But, for the sake of this issue, I'd strongly recommend including a sample schema and a brief code snippet that allows one to reproduce / validate whatever issue is being reported.

**Comment by RobbeSneyders** [comment] 2021-07-31 20:14
Closing in favor of #1409 which provides more information.

**Closed by RobbeSneyders** 2021-07-31 20:14 UTC
