### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by Acromonkey** [zalando/connexion#1255] opened 2020-06-17 07:53 UTC
### Description
I want to upload a file to the connexion server running with aiohttp. I am experiencing exactly the same problem as described in https://github.com/zalando/connexion/issues/975

Uploading a file seems to me as a very basic functionality, so I am surprised that this still fails. Is there any workaround or other way to upload a file?

Just to replicate my very special case:

```
 /upload:
    put:
      description: "Upload a dataset."
      operationId: main.upload_dataset
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
```

I have tried to send files via python requests and via postman:

1) Python request:
```
import requests
url = "http://0.0.0.0:5000/api/v1/upload"
files = {'file': open("dataset.jsonl", 'rb')}
resp = requests.request("PUT", url=url, headers=None, data=None, files=files)
```
2) Postman:
URL: localhost:5000/api/v1/upload
Body: KEY is the word "file" and VALUE is a reference to the file dataset.jsonl
Method: PUT

### Expected behaviour
Connexion should process the file and provide it via 
`connexion.request.files['file']` to the FLASK function that is called.

### Actual behaviour
Connexion fails before even executing the function code. In the module
`connexion/decorators/validation.py`, lines 159 to 162 are:
```
elif self.consumes[0] in FORM_CONTENT_TYPES:
    data = dict(request.form.items()) or (request.body if len(request.body) > 0 else {})
    data.update(dict.fromkeys(request.files, ''))  # validator expects string..
    logger.debug('%s validating schema...', request.url)
```
In debug mode, I can see that data is of type `bytes` because it took the value of `request.body` which means that if fails in the next step where it treats data as a dictionary.

### Steps to reproduce
Create a minimal endpoint with this configuration:
```
 /upload:
    put:
      description: "Upload a dataset."
      operationId: main.upload_dataset
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
```

Send any file to the endpoint, for example as I described above for python requests.

### Additional info:

Output of the commands:

- `python --version` 
Python 3.7.5

- `pip show connexion | grep "^Version\:"`
Version: 2.7.0

**Comment by Aeross** [comment] 2020-06-24 00:24
Yesterday, I had the exact same issue as #975 but with Axios and React. Connexion was returning: 

`data.update(dict.fromkeys(request.files, ''))  # validator expects string..`

while testing file uploads.

In my case, the issue were the headers. I just followed the suggestion at https://stackoverflow.com/a/47630754/2489998 to correctly include the 'multipart/form-data' part and that fixed the issue. 

Maybe this info can help you.

**Comment by RobbeSneyders** [comment] 2021-07-20 19:16
Closing as duplicate of #975.

**Closed by RobbeSneyders** 2021-07-20 19:16 UTC
